version: '3.9'

services:
  php:
    build:
      context: ./app/
      dockerfile: ../docker/dockerfile.php
    depends_on:
      - node
    ports:
      - 8080:80
    volumes:
      - ./app/:/var/www/html/

  node:
    build:
      context: ./app/
      dockerfile: ../docker/dockerfile.node
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./app/:/app/
    environment:
      - IS_PROD=0
    command: servePHP
